// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg5iFyGqyHfgBlQRaZxZDzluBjqdkrYNM',
    appId: '1:267149542914:web:2500218aadcd6f9552c91b',
    messagingSenderId: '267149542914',
    projectId: 'hammami-transport',
    authDomain: 'hammami-transport.firebaseapp.com',
    storageBucket: 'hammami-transport.firebasestorage.app',
    measurementId: 'G-DXQYX3YEEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0khTmYldfzy4jG83nR46YXE7NdMHNJEA',
    appId: '1:267149542914:android:93e108a3d5900e0b52c91b',
    messagingSenderId: '267149542914',
    projectId: 'hammami-transport',
    storageBucket: 'hammami-transport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3zpAPlx6KxNvCx7xi_0jv-D6ERCeOG50',
    appId: '1:267149542914:ios:f6d6d326e0e9fa0852c91b',
    messagingSenderId: '267149542914',
    projectId: 'hammami-transport',
    storageBucket: 'hammami-transport.firebasestorage.app',
    iosBundleId: 'com.example.hammamiTransportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3zpAPlx6KxNvCx7xi_0jv-D6ERCeOG50',
    appId: '1:267149542914:ios:f6d6d326e0e9fa0852c91b',
    messagingSenderId: '267149542914',
    projectId: 'hammami-transport',
    storageBucket: 'hammami-transport.firebasestorage.app',
    iosBundleId: 'com.example.hammamiTransportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg5iFyGqyHfgBlQRaZxZDzluBjqdkrYNM',
    appId: '1:267149542914:web:53399fa8b613e60052c91b',
    messagingSenderId: '267149542914',
    projectId: 'hammami-transport',
    authDomain: 'hammami-transport.firebaseapp.com',
    storageBucket: 'hammami-transport.firebasestorage.app',
    measurementId: 'G-F82L2FF8HS',
  );
}
